<?php
$file = 'backend/app/Resources/Account/Razorpay/RazorpayLinkedAccountResponseResource.php';
$content = file_get_contents($file);
$content = str_replace('namespace HiEvents\Resources\Account\Stripe;', 'namespace HiEvents\Resources\Account\Razorpay;', $content);
$content = str_replace('use HiEvents\Services\Application\Handlers\Account\Payment\Stripe\DTO\CreateStripeConnectAccountResponse;', 'use HiEvents\Services\Application\Handlers\Account\Payment\Razorpay\DTO\CreateRazorpayLinkedAccountResponse;', $content);
$content = str_replace('StripeConnectAccountResponseResource', 'RazorpayLinkedAccountResponseResource', $content);
$content = str_replace('CreateStripeConnectAccountResponse', 'CreateRazorpayLinkedAccountResponse', $content);
$content = str_replace('stripeConnectAccountType', 'razorpayLinkedAccountType', $content);
$content = str_replace('stripe_connect_account_type', 'razorpay_linked_account_type', $content);
$content = str_replace('stripeAccountId', 'razorpayAccountId', $content);
$content = str_replace('stripe_account_id', 'razorpay_account_id', $content);
file_put_contents($file, $content);

$file = 'backend/app/Resources/Account/Razorpay/RazorpayLinkedAccountsResponseResource.php';
$content = file_get_contents($file);
$content = str_replace('namespace HiEvents\Resources\Account\Stripe;', 'namespace HiEvents\Resources\Account\Razorpay;', $content);
$content = str_replace('use HiEvents\Services\Application\Handlers\Account\Payment\Stripe\DTO\GetStripeConnectAccountsResponseDTO;', 'use HiEvents\Services\Application\Handlers\Account\Payment\Razorpay\DTO\GetRazorpayLinkedAccountsResponseDTO;', $content);
$content = str_replace('use HiEvents\Services\Application\Handlers\Account\Payment\Stripe\DTO\StripeConnectAccountDTO;', 'use HiEvents\Services\Application\Handlers\Account\Payment\Razorpay\DTO\RazorpayLinkedAccountDTO;', $content);
$content = str_replace('StripeConnectAccountsResponseResource', 'RazorpayLinkedAccountsResponseResource', $content);
$content = str_replace('GetStripeConnectAccountsResponseDTO', 'GetRazorpayLinkedAccountsResponseDTO', $content);
$content = str_replace('StripeConnectAccountDTO', 'RazorpayLinkedAccountDTO', $content);
$content = str_replace('stripeConnectAccounts', 'razorpayLinkedAccounts', $content);
$content = str_replace('stripe_connect_accounts', 'razorpay_linked_accounts', $content);
$content = str_replace('stripeAccountId', 'razorpayAccountId', $content);
$content = str_replace('stripe_account_id', 'razorpay_account_id', $content);
$content = str_replace('primaryStripeAccountId', 'primaryRazorpayAccountId', $content);
$content = str_replace('primary_stripe_account_id', 'primary_razorpay_account_id', $content);
$content = str_replace('stripePlatform', 'razorpayPlatform', $content);
$content = str_replace('stripe_platform', 'razorpay_platform', $content);
file_put_contents($file, $content);
